DROP DATABASE if EXISTS Examen_SamuelGZ;
CREATE DATABASE Examen_SamuelGZ CHARACTER SET UTF8MB4 COLLATE UTF8MB4_SPANISH_CI;
USE Examen_SamuelGZ;

# EJERCICIO 1

CREATE TABLE CLIENTES (
	ID_CLIENTE	CHAR(10)			PRIMARY KEY,
	NOM_CLI		VARCHAR(30)		NOT NULL,
	DIRECCION	VARCHAR(30),
	LOCALIDAD	VARCHAR(30),
	TELEFONO		INT(9) 			NOT NULL,
	CONSTRAINT UNIQUE KEY UQ_CLIENTES_TELEFONO (TELEFONO)
);

# EJERCICIO 2

CREATE TABLE PEDIDOS (
	ID_PEDIDO		CHAR(10),
	ID_CLIENTE	CHAR(10)		NOT NULL,
	FECHA			DATE			NOT NULL,
	IMPORTE		DEC(10,2)	NOT NULL,
	CONSTRAINT PRIMARY KEY (ID_PEDIDO),
	CONSTRAINT FOREIGN KEY FK_PEDIDOS_CLIENTES (ID_CLIENTE) REFERENCES CLIENTES (ID_CLIENTE)
);

# EJERCICIO 3

CREATE TABLE PLATOS (
	ID_PLATO			CHAR(10)			PRIMARY KEY,
	DESC_PLATO 		VARCHAR(100)	NOT NULL,
	INGREDIENTES	VARCHAR(100)	NOT NULL,
	PRECIO			DEC(10,2)		NOT NULL
);

# EJERCICIO 4

CREATE TABLE DETALLE_PEDIDO (
	ID_PEDIDO	CHAR(10),
	ID_PLATO		CHAR(10),
	NUM_PLATOS	INT(2) 		NOT NULL,
	CONSTRAINT PRIMARY KEY (ID_PEDIDO, ID_PLATO),
	CONSTRAINT FOREIGN KEY FK_DETALLE_PEDIDO_PEDIDOS (ID_PEDIDO) REFERENCES PEDIDOS (ID_PEDIDO),
	CONSTRAINT FOREIGN KEY FK_DETALLE_PEDIDO_PLATOS (ID_PLATO) REFERENCES PLATOS (ID_PLATO)
);

# EJERCICIO 5

ALTER TABLE CLIENTES ADD COLUMN C_POSTAL INT(5);

# EJERCICIO 6

# En la página 91 del manual de MariaDB aparece el siguiente comando:
ALTER TABLE PEDIDOS DROP FOREIGN KEY if EXISTS FK_PEDIDOS_CLIENTES;

# EJERCICIO 7

ALTER TABLE PEDIDOS ADD CONSTRAINT FOREIGN KEY FK_PEDIDOS_CLIENTES (ID_CLIENTE) REFERENCES CLIENTES (ID_CLIENTE);

# EJERCICIO 8

ALTER TABLE CLIENTES RENAME COLUMN C_POSTAL TO CODIGO_POSTAL;

# EJERCICIO 9

# En la página 98 del manual de MariaDB aparece el siguiente comando:
ALTER TABLE PLATOS ADD CONSTRAINT ESTA_ENTRE CHECK (PRECIO >= 1 && PRECIO <= 1000);